- id: pixi-sync-environment
  name: Sync pixi environment with conda environment file
  entry: sync_environment
  files: (?:environment\.yml|pixi\.toml|pyproject\.toml|pixi\.lock)$
  language: python
  minimum_pre_commit_version: 2.9.2
